### ISSUE TITLE
Keith: Selecting library at top does not change library info in footer...

### ISSUE THREAD

**Issue by amy-actually** [frlux/tawny-owl-nuxt#2]
Selecting library at top does not change library info in footer and disables all internal links (event, service, blog, footer menu) but external links for collection or libguides still work. Links remain disabled even after re-selecting All Libraries.
https://github.com/fontana-regional-library/feathers-design-system/issues/64

**Comment by amy-actually** [comment]
This should be resolved as of March 19th update (now live)

**Comment by CKeithB** [comment]
Verified working
